### ISSUE TITLE
Cannot generate the charts

### ISSUE THREAD

**Issue by apete** [lessthanoptimal/Java-Matrix-Benchmark#12]
I've completed a benchmark execution, but I cannot generate the charts when the results for either MTJ-N or UJMP-N are included. If I remove both of those libraries (data sets) I get the charts, and also if I set "—PlotNative=false"

I have mailed you the complete results so you try this yourself.

Perhaps a good idea to still generate the other charts even if 1 chart fails.

sailfish:Java-Matrix-Benchmark apete$ java -jar benchmark.jar plotRuntime --PlotNative=true /Users/apete/Developer/apete_ws/Java-Matrix-Benchmark/results/runtime_04-04-2018-17_45_49/
PlotNative = true
Parsing /Users/apete/Developer/apete_ws/Java-Matrix-Benchmark/results/runtime_04-04-2018-17_45_49/
Exception in thread "main" java.lang.RuntimeException: add some more
	at jmbench.plots.OperationsVersusSizePlot.getColor(OperationsVersusSizePlot.java:209)
	at jmbench.plots.OperationsVersusSizePlot._addErrors(OperationsVersusSizePlot.java:144)
	at jmbench.plots.OperationsVersusSizePlot.addResults(OperationsVersusSizePlot.java:134)
	at jmbench.tools.runtime.evaluation.RuntimeResultPlotter.variabilityPlots(RuntimeResultPlotter.java:365)
	at jmbench.tools.runtime.evaluation.PlotRuntimeResults.createPlots(PlotRuntimeResults.java:145)
	at jmbench.tools.runtime.evaluation.PlotRuntimeResults.plot(PlotRuntimeResults.java:121)
	at jmbench.tools.runtime.evaluation.PlotRuntimeResults.main(PlotRuntimeResults.java:372)
	at jmbench.tools.BenchmarkToolsMasterApp.main(BenchmarkToolsMasterApp.java:106)

**Comment by lessthanoptimal** [comment]
I'm going to work on this soon. Just fixed the ambiguous time parameter and pushed it to github. It now prints out the maximum duration for a single test. Also limited it to a single test per JVM instance. That parameter was hidden from you but before it would run about 5 tests in a single instance to avoid the warm up period.

**Comment by lessthanoptimal** [comment]
ok that was quick. Fixed pushed. Just make sure you clear out old jars first

./gradlew clean;./gradlew createRuntimeJars;./gradlew benchmark
